name: eco_sustain
description: A new Flutter project.

publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  lucide_icons: ^0.257.0   # ✅ Added Lucide icons
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  
  # Firebase packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  google_sign_in: ^6.2.2
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # Additional utilities
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.2.1          # Environment variables
  
  # Learning content packages
  youtube_player_flutter: ^9.0.3  # YouTube video player
  flutter_markdown: ^0.7.4+1      # Markdown renderer for articles
  url_launcher: ^6.3.1            # Launch URLs
  flutter_quill: ^11.5.0          # Rich text editor (for admin panel)
  cached_network_image: ^3.4.1   # Cache images for better performance

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - .env

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/logo.png"
  adaptive_icon_background: "#2ECC71"  # EcoSustain green color
  adaptive_icon_foreground: "lib/assets/images/logo.png"

