// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwPDAeWImyrROHbs69Up89FLS4aYwmnc',
    appId: '1:851189435727:web:33fe0b199ea7e276ff493a',
    messagingSenderId: '851189435727',
    projectId: 'eco-sustain-51b9b',
    authDomain: 'eco-sustain-51b9b.firebaseapp.com',
    storageBucket: 'eco-sustain-51b9b.firebasestorage.app',
    measurementId: 'G-BB1W12WTFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYO930CM6Ctk8SdK9l3RrDF2uz1FfqKo',
    appId: '1:851189435727:android:f580ac8729c44a5fff493a',
    messagingSenderId: '851189435727',
    projectId: 'eco-sustain-51b9b',
    storageBucket: 'eco-sustain-51b9b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwPDAeWImyrROHbs69Up89FLS4aYwmnc',
    appId: '1:851189435727:web:0a4158df8653f3c2ff493a',
    messagingSenderId: '851189435727',
    projectId: 'eco-sustain-51b9b',
    authDomain: 'eco-sustain-51b9b.firebaseapp.com',
    storageBucket: 'eco-sustain-51b9b.firebasestorage.app',
    measurementId: 'G-9RRF9R48NB',
  );
}
